// A long rotating list of measurable commitments. These cycle through the goal
// input as handwritten placeholders — never static, never generic.
export const GOAL_EXAMPLES: string[] = [
  "Finish Chapter 4 of Physics and solve exercises 1–20.",
  "Chest & Triceps workout — Bench 3×8, Incline DB 3×10, Pushdowns 3×12.",
  "Complete the homepage redesign and deploy it.",
  "Write 1500 words. No editing until the count is hit.",
  "Edit the client's landing page and send it over.",
  "Solve 30 aptitude questions and review every mistake.",
  "Read pages 40–90 and write 5 lines of notes per chapter.",
  "Clear all 8 open tickets on the sprint board.",
  "Revise Organic Chemistry mechanisms, then self-test blind.",
  "Record and edit one full video for the channel.",
  "Run 5 km, then stretch for 10 minutes.",
  "Finish the authentication page and push the commit.",
  "Draft the entire cover letter and proofread it twice.",
  "Memorise 40 new vocabulary words and test yourself.",
  "Complete Assignment 3 — all 6 questions, fully worked.",
  "Clean the entire room, including under the bed.",
  "Practice piano scales for 30 minutes, then one full piece.",
  "Answer every unread email and empty the inbox.",
  "Build the pricing section and make it responsive.",
  "Solve 15 LeetCode mediums on arrays.",
  "Write the first draft of the essay — intro, 3 body paragraphs, conclusion.",
  "Study 2 past papers under exam conditions.",
  "Back and Biceps — Deadlift 4×5, Rows 3×10, Curls 3×12.",
  "Prepare the full slide deck for tomorrow's meeting.",
  "Do 100 push-ups and 100 squats.",
  "Finish the maths homework — all 12 sums, checked.",
  "Design 3 logo concepts in Figma.",
  "Read 50 pages of the textbook and highlight key ideas.",
  "Refactor the API layer and make all tests pass.",
  "Write and schedule 7 posts for the week.",
  "Complete the entire tax spreadsheet for last quarter.",
  "Learn the first 20 kanji from the list, then write each 5 times.",
  "Sketch 10 thumbnails for the illustration.",
  "Rewrite the whole About page copy.",
  "Do a 45-minute leg session — Squats 4×8, Lunges 3×12, Calves 4×15.",
  "Finish the lab report — method, results, discussion.",
  "Watch the lecture and summarise it in one page.",
  "Fix the 6 bugs listed in the tracker.",
  "Practice 20 minutes of speaking, then 20 of listening.",
  "Complete the onboarding flow wireframes.",
  "Meal prep for 5 days and clean the kitchen.",
  "Write 2000 words of the dissertation chapter.",
  "Study Chapter 7 and make 30 flashcards.",
  "Edit the podcast episode end to end.",
  "Solve every question in the derivatives worksheet.",
  "Send 20 cold emails with personalised first lines.",
  "Finish the Figma prototype and share the link.",
  "Do the entire chest workout without touching the phone.",
  "Translate the 3-page document and proofread it.",
  "Complete the React tutorial through module 6.",
  "Organise every file on the desktop into folders.",
  "Write the full script for the next video.",
  "Study for 2 hours: 40 min Biology, 40 min Chemistry, 40 min Physics.",
  "Build the contact form and connect it to the database.",
  "Read the entire research paper and take structured notes.",
  "Complete 3 rounds of the HIIT circuit.",
  "Finish the client invoice and send it before the deadline.",
  "Practice the guitar solo until it's clean at full tempo.",
  "Do all 25 integration problems from the sheet.",
  "Plan the entire week — calendar, tasks, meals.",
  "Write documentation for every public function.",
  "Complete the mock interview and review the recording.",
  "Draw one full character from reference, inked.",
  "Read 3 chapters of the novel and note every theme.",
  "Fix the mobile layout on all 5 pages.",
  "Study the entire Cold War unit and outline the essay.",
  "Do 200 skips, 3 sets of planks, 15 minutes of stretching.",
  "Finish the pitch deck and rehearse it twice.",
  "Solve the 10 hardest problems from last year's paper.",
  "Write the README and set up the repo properly.",
  "Complete the CAD model for the bracket.",
  "Learn the whole song by heart, lyrics and chords.",
  "Rewrite the resume and tailor it to 3 job posts.",
  "Do the entire Anki backlog — every due card.",
  "Build the dashboard charts with real data.",
  "Read 60 pages and write a one-page summary.",
  "Complete the swimming set — 20 × 50m.",
  "Finish the poster design and export print-ready files.",
  "Study 3 hours of anatomy with zero interruptions.",
  "Set up the CI pipeline and get a green build.",
  "Write 5 pages of the short story.",
  "Complete the full statistics problem set.",
  "Record 10 takes of the voiceover and pick the best.",
  "Do a full deep clean of the bathroom and kitchen.",
  "Finish the accounting reconciliation for the month.",
  "Practice 100 free throws.",
  "Learn and implement binary search trees from scratch.",
  "Edit 50 photos from the shoot and deliver the gallery.",
  "Read the entire contract and mark every risky clause.",
  "Complete the Spanish lesson and 30 minutes of review.",
  "Build and ship the settings page.",
  "Write out every formula from Chapter 9 by memory.",
  "Do a 60-minute full-body session, no rest over 90 seconds.",
  "Finish the market research and summarise 10 competitors.",
  "Draft the entire newsletter and schedule it.",
  "Solve 20 physics numericals on momentum.",
  "Complete the migration script and test it locally.",
  "Study until the whole syllabus for Unit 3 is covered.",
  "Paint the underlayer of the canvas completely.",
  "Reply to every message in the support queue.",
  "Write the business plan's financial section.",
  "Revise all 12 lecture slides and self-quiz twice.",
];
