// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'
import { createRemoteJWKSet, decodeJwt, jwtVerify } from 'jose'



function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    
    const SUPABASE_URL = process.env['SUPABASE_URL'];
    const SUPABASE_PUBLISHABLE_KEY = process.env['SUPABASE_PUBLISHABLE_KEY'];

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }
    
    const request = getRequest();

    if (!request?.headers) {
      throw new Error('Unauthorized: No request headers available');
    }

    const authHeader = request.headers.get('authorization');

    if (!authHeader) {
      throw new Error('Unauthorized: No authorization header provided');
    }

    if (!authHeader.startsWith('Bearer ')) {
      throw new Error('Unauthorized: Only Bearer tokens are supported');
    }

    const token = authHeader.replace('Bearer ', '');
    if (!token) {
      throw new Error('Unauthorized: No token provided');
    }

    // Allow developer mock tokens
    if (token.startsWith('mock-token-')) {
      const userId = token.replace('mock-token-', '');
      console.log('[Auth] Developer login detected, bypassing JWT validation');
      
      const supabase = createClient<Database>(
        SUPABASE_URL!,
        SUPABASE_PUBLISHABLE_KEY!,
        {
          global: {
            fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY!),
          },
          auth: {
            storage: undefined,
            persistSession: false,
            autoRefreshToken: false,
          },
        }
      );

      return next({
        context: {
          supabase,
          userId,
          claims: { sub: userId, isDev: true },
        },
      });
    }

    if (token.split('.').length !== 3) {
      throw new Error('Unauthorized: Invalid token');
    }

    const firebaseProjectId = 'loin-813a3'
    const firebaseIssuer = `https://securetoken.google.com/${firebaseProjectId}`
    let firebaseCandidate = false
    try {
      // This only selects the verification path. Authorization relies on the
      // signature, issuer, and audience checks below, never this decoded value.
      firebaseCandidate = decodeJwt(token).iss === firebaseIssuer
    } catch {
      // Supabase Auth tokens are validated by Supabase below.
    }
    let claims: Record<string, unknown>
    let userId: string
    let isFirebaseToken = false
    if (firebaseCandidate) {
      let verified
      try {
        verified = await jwtVerify(
          token,
          createRemoteJWKSet(new URL('https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com')),
          { issuer: firebaseIssuer, audience: firebaseProjectId },
        )
      } catch (error) {
        // Do not log the bearer token. These details distinguish stale/wrong
        // project tokens from bad signatures or an unavailable Google key set.
        console.error('[Auth] Firebase ID token verification failed:', error instanceof Error ? error.message : 'unknown verification error')
        throw new Error('Unauthorized: Firebase ID token verification failed')
      }

      if (verified.payload.role !== 'authenticated') {
        throw new Error('Unauthorized: Firebase account is missing the authenticated role claim; refresh the ID token after setting Firebase custom claims')
      }
      const loinUserId = verified.payload.loin_user_id
      if (typeof loinUserId !== 'string' || !/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(loinUserId)) {
        throw new Error('Unauthorized: Firebase account is missing a valid LOIN user ID claim')
      }
      claims = verified.payload
      userId = loinUserId
      isFirebaseToken = true
    } else {
      // Existing web Supabase sessions keep their current auth flow.
      const supabase = createClient<Database>(
        SUPABASE_URL!,
        SUPABASE_PUBLISHABLE_KEY!,
        {
          global: { fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY!) },
          auth: { storage: undefined, persistSession: false, autoRefreshToken: false },
        },
      )
      const { data, error } = await supabase.auth.getClaims(token)
      if (error || !data?.claims?.sub) {
        console.error('[Auth] Supabase access token validation failed:', error?.message ?? 'missing subject claim')
        throw new Error('Unauthorized: Invalid Supabase access token')
      }
      claims = data.claims as Record<string, unknown>
      userId = String(data.claims.sub)
    }

    const supabase = createClient<Database>(
      SUPABASE_URL!,
      SUPABASE_PUBLISHABLE_KEY!,
      {
        global: {
          fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY!),
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      }
    );

    return next({
      context: {
        supabase,
        userId,
        claims: { ...claims, isFirebase: isFirebaseToken },
      },
    });
  },
);
